package com.featuredeliveryintelligence.fdi.orchestration;

public enum KnowledgeRoute {
    WORKSPACE_SEMANTIC,
    WORKSPACE_PROCEDURAL,
    SKILL_IMPROVEMENT,
    CONTROL_IMPROVEMENT,
    SWARM_CORE_IMPROVEMENT,
    RUNTIME_BINDING_IMPROVEMENT,
    PRODUCT_KNOWLEDGE_PROPOSAL,
    MULTICA_PLATFORM_ISSUE,
    MISSION_HISTORY,
    DIRECT_TKMS_PUBLICATION
}
