package com.featuredeliveryintelligence.fdi.reverse.cli;

import com.featuredeliveryintelligence.fdi.reverse.ReverseContractException;
import com.featuredeliveryintelligence.fdi.reverse.evidence.EvidenceChannelRecord;
import com.featuredeliveryintelligence.fdi.reverse.evidence.ReverseEvidenceBundle;
import com.featuredeliveryintelligence.fdi.reverse.evaluation.ReverseComparisonReport;
import com.featuredeliveryintelligence.fdi.reverse.evaluation.ReverseComparisonReportJson;
import com.featuredeliveryintelligence.fdi.reverse.evaluation.ReverseEvaluatorTruth;
import com.featuredeliveryintelligence.fdi.reverse.evaluation.ReverseProposalComparator;
import com.featuredeliveryintelligence.fdi.reverse.evaluation.ReverseSealedPackage;
import com.featuredeliveryintelligence.fdi.reverse.generator.DeterministicReverseProposalGenerator;
import com.featuredeliveryintelligence.fdi.reverse.generator.ReverseProposalPackageJson;
import com.featuredeliveryintelligence.fdi.reverse.input.deliveryhistory.DeliveryHistoryInputAdapter;
import com.featuredeliveryintelligence.fdi.reverse.input.structural.StructuralEvidenceAdapter;
import com.featuredeliveryintelligence.fdi.reverse.input.structural.StructuralSnapshotBinding;
import com.featuredeliveryintelligence.fdi.reverse.input.testbehavior.TestBehaviorEvidenceAdapter;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.io.IOException;
import java.io.PrintStream;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Packaged CLI for PKB-BL-009 deterministic Reverse proposal generation
 * (Slice G wiring): {@code reverse-propose --repository-root PATH
 * [--repository-id ID] [--revision SHA] [--graph PATH] [--graph-sha256 HEX]
 * [--output-dir PATH]}. The CLI binds the exact Petclinic revision and the
 * frozen SHA-256 digests of the structural, test-behavior, and delivery
 * inputs through the Slice B/C/D adapters, verifies the bundle digest
 * binding, generates the proposal package with
 * {@link DeterministicReverseProposalGenerator}, re-validates the sealed
 * bytes through {@link ReverseSealedPackage#load(byte[])}, and only then
 * runs the evaluator-only comparison against the frozen evaluator surface,
 * preserving the envelope rule that generation never reads evaluator truth
 * and comparison runs only after the package is sealed.
 *
 * <p>The immutable run directory is maintained fail-closed: an existing
 * artifact must equal the regenerated bytes exactly, otherwise the run
 * refuses with exit 1 and leaves the artifact untouched; absent artifacts
 * are written. Generation and serialization are deterministic and carry no
 * wall-clock fields, so two clean runs over identical inputs compare
 * byte-equal. Exit 0 on success; exit 1 with a compact
 * {@code {"status": "ERROR", "failure": ..., "error": ...}} JSON on stdout
 * for any fail-closed refusal; exit 2 on usage errors. Emitted proposals
 * remain {@code PROPOSAL_ONLY} with {@code semantic_publication_allowed ==
 * false}; the CLI publishes no Product semantics.
 */
public final class ReverseProposalCli {

    /** CLI command name dispatched from {@code FdiApplication}. */
    public static final String COMMAND = "reverse-propose";

    private static final String USAGE = "usage: " + COMMAND
            + " --repository-root PATH [--repository-id ID] [--revision SHA]"
            + " [--graph PATH] [--graph-sha256 HEX] [--output-dir PATH]";

    private static final String DEFAULT_REPOSITORY_ID = "spring-petclinic";
    private static final String DEFAULT_REVISION = "818c4136ea971c21674525f9053de0d9c7ad8cfe";
    private static final String DEFAULT_GRAPH_PATH =
            "validation/pkb001/reverse-pkb-bl009-petclinic-001/provider-discovery/graph-petclinic-818c413-main-and-test.json";
    private static final String DEFAULT_GRAPH_SHA256 =
            "5ff8454ae758c8b8ffb1e755ff7c2124efd233388f4f901d8d964b04977c27ca";
    private static final String DEFAULT_OUTPUT_DIR =
            "validation/pkb001/reverse-pkb-bl009-petclinic-001/proposal-run";
    private static final String PROPOSAL_PACKAGE_FILE = "proposal-package.json";
    private static final String COMPARISON_REPORT_FILE = "comparison-report.json";

    private ReverseProposalCli() { }

    public static boolean handles(String[] args) {
        return args != null && args.length > 0 && COMMAND.equals(args[0]);
    }

    public static int run(String[] args, PrintStream stdout, PrintStream stderr) {
        final Options options;
        try {
            options = parse(args);
        } catch (CliArgumentsException failure) {
            stderr.println(USAGE);
            stderr.println(COMMAND + ": error: " + failure.getMessage());
            return 2;
        }
        try {
            Path root = options.repositoryRoot().toAbsolutePath().normalize();

            EvidenceChannelRecord structural = StructuralEvidenceAdapter.load(
                    new StructuralSnapshotBinding(
                            options.repositoryId(), options.revision(),
                            options.graphPath(), options.graphSha256(),
                            "graphify", "frozen Graphify snapshot via CodeIntelligenceProvider"),
                    root);
            EvidenceChannelRecord testBehavior = TestBehaviorEvidenceAdapter.loadAccepted(root);
            EvidenceChannelRecord delivery = DeliveryHistoryInputAdapter.load(
                    root, options.repositoryId(), options.revision(),
                    DeliveryHistoryInputAdapter.PINNED_INPUT_SHA256);
            ReverseEvidenceBundle bundle = new ReverseEvidenceBundle(
                    options.repositoryId(), options.revision(), "1",
                    List.of(structural, testBehavior, delivery));
            ReverseEvidenceBundle.verifyInputDigests(bundle, root);

            // Generation and sealing complete before evaluator truth is loaded:
            // the sealed bytes are fixed here and the comparison below can
            // never feed back into generation.
            byte[] sealedPackage = ReverseProposalPackageJson.write(
                    new DeterministicReverseProposalGenerator().propose(bundle));
            ReverseSealedPackage.load(sealedPackage);

            ReverseComparisonReport report = ReverseProposalComparator.compare(
                    sealedPackage, ReverseEvaluatorTruth.load(root), bundle);
            byte[] comparisonReport = ReverseComparisonReportJson.write(report);

            Path outputDirectory = Path.of(options.outputDir()).toAbsolutePath().normalize();
            Path packageFile = writeImmutable(
                    outputDirectory.resolve(PROPOSAL_PACKAGE_FILE), sealedPackage);
            Path reportFile = writeImmutable(
                    outputDirectory.resolve(COMPARISON_REPORT_FILE), comparisonReport);

            ObjectNode status = JsonNodeFactory.instance.objectNode();
            status.put("status", "OK");
            status.put("repository_id", options.repositoryId());
            status.put("canonical_revision", options.revision());
            status.put("output_dir", outputDirectory.toString());
            status.put("proposal_package", packageFile.toString());
            status.put("proposal_package_sha256", sha256Hex(sealedPackage));
            status.put("comparison_report", reportFile.toString());
            status.put("comparison_report_sha256", sha256Hex(comparisonReport));
            status.put("capabilities", report.capabilityMatch().proposedCapabilities());
            status.put("scenarios", report.evidenceChannelCoverage().allThreeChannels().scenarios());
            status.put("evidence_gaps", gapCount(sealedPackage));
            stdout.println(status.toString());
            return 0;
        } catch (ReverseContractException refusal) {
            stdout.println(errorDocument(refusal.failure().name(), refusal.getMessage()).toString());
            return 1;
        } catch (IllegalArgumentException | IOException failure) {
            stdout.println(errorDocument(
                    "MISSING_INPUT",
                    failure.getMessage() == null ? failure.toString() : failure.getMessage()).toString());
            return 1;
        }
    }

    private static ObjectNode errorDocument(String failure, String error) {
        ObjectNode document = JsonNodeFactory.instance.objectNode();
        document.put("status", "ERROR");
        document.put("failure", failure);
        document.put("error", error);
        return document;
    }

    /**
     * Writes the artifact when absent; when present, fails closed unless the
     * existing bytes equal the regenerated bytes exactly, so a committed
     * immutable artifact can never drift or be overwritten.
     */
    private static Path writeImmutable(Path absolute, byte[] regenerated) throws IOException {
        if (Files.exists(absolute)) {
            byte[] existing = Files.readAllBytes(absolute);
            if (!MessageDigest.isEqual(existing, regenerated)) {
                throw new ReverseContractException(
                        com.featuredeliveryintelligence.fdi.reverse.ReverseFailure.DIGEST_MISMATCH,
                        "existing artifact drifted from regenerated bytes: " + absolute);
            }
            return absolute;
        }
        Path parent = absolute.getParent();
        if (parent != null) Files.createDirectories(parent);
        Files.write(absolute, regenerated);
        return absolute;
    }

    private static int gapCount(byte[] sealedPackage) {
        try {
            com.fasterxml.jackson.databind.JsonNode document =
                    new com.fasterxml.jackson.databind.ObjectMapper().readTree(sealedPackage);
            return document.path("evidence_gaps").size();
        } catch (IOException failure) {
            throw new UncheckedIOException("sealed package does not parse: " + failure, failure);
        }
    }

    private static String sha256Hex(byte[] bytes) {
        try {
            return hex(MessageDigest.getInstance("SHA-256").digest(bytes));
        } catch (NoSuchAlgorithmException impossible) {
            throw new IllegalStateException("SHA-256 is unavailable", impossible);
        }
    }

    private static String hex(byte[] bytes) {
        StringBuilder builder = new StringBuilder(bytes.length * 2);
        for (byte value : bytes) builder.append(String.format("%02x", value));
        return builder.toString();
    }

    private static Options parse(String[] args) {
        if (!handles(args)) {
            throw new CliArgumentsException("expected command " + COMMAND);
        }
        Map<String, String> values = new LinkedHashMap<>();
        for (int index = 1; index < args.length; index++) {
            String option = args[index];
            String value;
            int equalsAt = option.indexOf('=');
            if (option.startsWith("--") && equalsAt > 2) {
                value = option.substring(equalsAt + 1);
                option = option.substring(0, equalsAt);
            } else if (index + 1 < args.length) {
                value = args[++index];
            } else {
                throw new CliArgumentsException("argument " + option + ": expected one argument");
            }
            switch (option) {
                case "--repository-root", "--repository-id", "--revision",
                        "--graph", "--graph-sha256", "--output-dir" -> {
                    if (values.containsKey(option)) {
                        throw new CliArgumentsException("duplicate option " + option);
                    }
                    values.put(option, value);
                }
                default -> throw new CliArgumentsException("unknown argument " + option);
            }
        }
        require(values, "--repository-root");
        return new Options(
                Path.of(values.get("--repository-root")),
                values.getOrDefault("--repository-id", DEFAULT_REPOSITORY_ID),
                values.getOrDefault("--revision", DEFAULT_REVISION),
                values.getOrDefault("--graph", DEFAULT_GRAPH_PATH),
                values.getOrDefault("--graph-sha256", DEFAULT_GRAPH_SHA256),
                values.getOrDefault("--output-dir", DEFAULT_OUTPUT_DIR));
    }

    private static void require(Map<String, String> values, String option) {
        if (!values.containsKey(option) || values.get(option).isBlank()) {
            throw new CliArgumentsException("missing required option " + option);
        }
    }

    private record Options(
            Path repositoryRoot,
            String repositoryId,
            String revision,
            String graphPath,
            String graphSha256,
            String outputDir) { }

    private static final class CliArgumentsException extends IllegalArgumentException {
        private CliArgumentsException(String message) {
            super(message);
        }
    }
}
