package com.featuredeliveryintelligence.fdi;import com.featuredeliveryintelligence.fdi.validation.CanonicalBaseGate;import com.featuredeliveryintelligence.fdi.validation.Dev204Validation;import com.featuredeliveryintelligence.fdi.validation.VerificationAccounting;import com.featuredeliveryintelligence.fdi.feature.FeatureDiscovery;import com.featuredeliveryintelligence.fdi.feature.FeatureKnowledgePlan;import com.featuredeliveryintelligence.fdi.feature.RealizationTraversal;import com.featuredeliveryintelligence.fdi.product.ProductSemantics;import com.featuredeliveryintelligence.fdi.product.ProductKnowledgeMaintenance;import com.featuredeliveryintelligence.fdi.structural.graphify.GraphifyAdapter;import com.featuredeliveryintelligence.fdi.structural.graphify.GraphifyBindingAttestor;import com.featuredeliveryintelligence.fdi.structural.graphify.GraphifyBindingEvidence;import com.featuredeliveryintelligence.fdi.structural.graphify.GraphifyTransport;import com.featuredeliveryintelligence.fdi.structural.api.CodeIntelligenceProvider;import com.featuredeliveryintelligence.fdi.structural.api.SnapshotBindingAttestor;import com.featuredeliveryintelligence.fdi.structural.api.StructuralIntelligence;import com.featuredeliveryintelligence.fdi.structural.api.StructuralMaintenance;import com.featuredeliveryintelligence.fdi.shared.RuntimeMaps;import com.featuredeliveryintelligence.fdi.shared.RuntimeContractException;
import static org.assertj.core.api.Assertions.*;import java.util.*;import org.junit.jupiter.api.Test;
class ReviewRegressionTests{
 @Test void bindingRejectsRepositoryRevisionMismatch(){Map<String,Object>s=Map.of("snapshot_id","s","provider_scope_id","g","provider_ref","r","repositories",List.of(Map.of("repository_id","repo","canonical_revision","a".repeat(40))));GraphifyBindingAttestor a=new GraphifyBindingAttestor(x->Map.of("queryable",true,"runtime_version","1.0.0","wire_version","mcp-1","repository_bindings",List.of(Map.of("repository_id","repo","indexed_revision","b".repeat(40)))),"fdi");assertThatThrownBy(()->a.attest(s)).hasMessageContaining("revision");}
 @Test void maintenanceOnlySignalsMatchingRepositories(){Map<String,Object>o=Map.of("observation_id","o","relation_type","API","non_authoritative",true,"from",Map.of("repository_id","r1"),"to",Map.of());Map<String,Object>d=Map.of("non_authoritative",true,"added",List.of(o),"removed",List.of());List<Map<String,Object>>a=List.of(Map.of("asset_ref_id","a","repository_ids",List.of("r2"),"publication_state","PUBLISHED","validity_state","ACTIVE"));assertThat(StructuralMaintenance.deriveSignals(d,a,List.of("API"),10).get("signals")).isEqualTo(List.of());}
 @Test void featurePlanCannotPromoteForbiddenMode(){Map<String,Object>t=Map.of("template_id","t","knowledge_role","SEMANTICS","allowed_authority_dimensions",List.of("DURABLE_CONSTRAINT"),"allowed_modes",List.of("OPTIONAL"),"may_promote_to_required",false);Map<String,Object>s=Map.of("skill_id","s","skill_revision","1","context_requirement_templates",List.of(t));Map<String,Object>i=Map.of("template_id","t","knowledge_role","SEMANTICS","authority_dimension","DURABLE_CONSTRAINT","mode","REQUIRED");assertThatThrownBy(()->FeatureKnowledgePlan.compile(Map.of("plan_id","p","revision",1,"items",List.of(i)),s)).hasMessageContaining("mode");}
 @Test void productSemanticsRequiresTrustProfile(){Map<String,Object>a=new HashMap<>();a.put("fdi_asset_version","0.1");a.put("asset_family","PRODUCT");a.put("asset_type","PA-01_MINIMAL_PRODUCT_SEMANTICS");a.put("asset_id","a");a.put("asset_revision",1);a.put("descriptor_ref","d");a.put("content_ref","c");a.put("owner","o");a.put("as_of","now");a.put("publication_state","DRAFT");a.put("validity_state","NOT_APPLICABLE");a.put("scope",Map.of("products",List.of("p"),"systems",List.of(),"repositories",List.of(),"environments",List.of()));a.put("product",Map.of("product_id","p"));assertThatThrownBy(()->ProductSemantics.validate(a,List.of())).hasMessageContaining("trust_profile");}
 @Test void traversalRejectsInvalidTypedEdge(){Map<String,Object>node=Map.of("id","a","type","CAPABILITY","product_scope","p");Map<String,Object>bad=Map.of("relation_id","r","relation_type","CONTAINS","from",node,"to",Map.of("id","b","type","REPOSITORY","product_scope","p"),"declared_by_profile",true,"publication_state","PUBLISHED","validity_state","ACTIVE");Map<String,Object>policy=Map.of("max_depth",2,"max_edges_examined",10,"max_paths_per_repository",2,"allowed_relation_types",List.of("CONTAINS"),"allowed_product_scope",List.of("p"),"lifecycle_required","PUBLISHED_ACTIVE");assertThatThrownBy(()->RealizationTraversal.deriveRepositoryCandidates(List.of(node),List.of(bad),policy)).hasMessageContaining("typed");}
}
