'use strict';
const path=require('path'),{createOperations}=require('./operations.cjs');
const terminal=r=>['completed','cancelled','failed'].includes(r.status);
function dispatchPending({professional,childPending,sameIssueBindingPending,sameIssueRequest,producerCount}){return !!professional&&!!(childPending||sameIssueBindingPending||sameIssueRequest&&producerCount===0);}
function initialDeadlineAt(startedAt){const t=Date.parse(startedAt);if(typeof startedAt!=='string'||!Number.isFinite(t))throw Error('INITIAL_START_ABSENT');return t+300000;}
function closureOperationTimeout(target,now=performance.now()){const left=Math.floor(target-now);if(!Number.isFinite(left)||left<1)throw Error('CLOSURE_DEADLINE_EXPIRED');return Math.min(20000,left);}
function initialStartDisposition(run){if(run.status==='dispatched'&&run.started_at===null)return 'WAIT_DISPATCH_ACK';initialDeadlineAt(run.started_at);if(!['running','completed','cancelled','failed'].includes(run.status))throw Error('UNSUPPORTED_INITIAL_STATUS');return 'HAS_REAL_START';}

// Interpretation is an evidence view, never a new operation or role verdict.
function createObservationRecorder(state,context,interpret){
 if(!context||!Array.isArray(context.actors)||!context.actors.length||!context.providerPin||!/^([a-f0-9]{64})$/.test(context.providerPin.sha256)||typeof context.providerPin.path!=='string'||!Number.isSafeInteger(context.providerPin.bytes)||context.providerPin.bytes<1||typeof interpret!=='function')throw Error('OBSERVATION_CONTEXT_REQUIRED');
 context=structuredClone(context);
 return function record(method,raw,run,options={}){
  const bound=state.boundRuns?.[run?.id],metadata=options.kind==='RUN_METADATA';
  if(!bound||!state.ownedIssues.includes(run.issue_id)||run.workspace_id!==context.workspace||run.runtime_id!==context.runtime||!context.actors.includes(run.agent_id)||['id','issue_id','agent_id','workspace_id','runtime_id'].some(k=>run[k]!==bound[k])||(!metadata&&(!Number.isSafeInteger(run.observedSeq)||run.observedSeq<1)))throw Error('OBSERVATION_BINDING_GAP');
  const value={method,binding:{actor:run.agent_id,workspace:run.workspace_id,runtime:run.runtime_id,run:run.id,issue:run.issue_id,kind:metadata?'RUN_METADATA':'TRACE_REQUEST',seq:metadata?null:run.observedSeq,callId:metadata?null:run.observedCallId??null},provider:structuredClone(context.providerPin),raw:structuredClone(raw),interpretation:interpret(raw)};
  state.methodObservations??=[];if(!state.methodObservations.some(x=>JSON.stringify(x)===JSON.stringify(value)))state.methodObservations.push(value);return value;
 };
}

async function main(context,injected={}){
const operations=createOperations(context,injected),{fs,op,admission,read,readNamed,save,pin,assertPin,assertNamedDependency,ws,runtime}=operations;
const a=admission(),review=read('PHASE-ZG-EXECUTION-REVIEW.json');if(review.verdict!=='APPROVE_EXACT_NATIVE_EXECUTION'||review.executionSubjectSha256!==pin('PHASE-ZG-EXECUTION-SUBJECT.json').sha256)throw Error('exact admission absent');if(a.evidenceRoot!==operations.evidenceRoot||a.workspace!==ws||a.runtime!==runtime||a.caller!==operations.caller)throw Error('SUBJECT_CONTEXT_MISMATCH');for(const p of a.dependencies)assertPin(p);
for(const file of ['controller.cjs','capture-method.cjs','routing-method.cjs','operations.cjs','../role-unit-evidence-v3.mjs','../role-paged-source-read-evidence-r1.mjs']){const required=path.resolve(__dirname,file);if(!a.dependencies.some(p=>path.resolve(operations.evidenceRoot,p.path)===required))throw Error('CURRENT_CONSUMER_PIN_REQUIRED');}
for(const name of ['PHASE-ZG-PREPARATION.json','phaseZG-orchestrator.stdout','phaseZG-coder.stdout'])assertNamedDependency(a,name);
const providerPath=path.resolve(__dirname,'../role-unit-evidence-v3.mjs');if(a.deadlineProvider.path!==providerPath)throw Error('CURRENT_PROVIDER_REQUIRED');assertPin(a.deadlineProvider);
const prep=readNamed('PHASE-ZG-PREPARATION.json'),key=context.caseKey,c=prep.cases.find(x=>x.key===key),mode=c?.actor==='9e98e1d4-7bb5-4efe-9b32-e90962683e71'?'coder':key;if(!c||!a.allowedCases.includes(key))throw Error('case not admitted');
if(fs.readdirSync(c.cwd).length)throw Error('fresh root changed before trigger');const sf='phaseZG-'+key+'-state.json';if(fs.existsSync(sf))throw Error('case already observed');
const s={key,issue:c.issue,ownedIssues:[c.issue],runs:[],snapshots:{},boundRuns:{},requests:[],violations:[],polls:0,startedObservationAt:new Date().toISOString(),controller:'ASYNC_CONTINUOUS_FOREGROUND',methodSource:{executionSubjectSha256:review.executionSubjectSha256,dependencies:a.dependencies}};save(sf,s);
const {startOwnedCaptureDeadline,interpretMethodObservation}=await import('../role-unit-evidence-v3.mjs'),watches=new Map();let caseStop=null,stopPromise=null,initialDeadline=null,caseTargetMono=null,pendingTimer=null,closureTargetMono=null,dispatchTimer=null,dispatchWaitReads=0,assignmentAckMono=null;
const record=createObservationRecorder(s,{workspace:ws,runtime,actors:[c.actor,'9e98e1d4-7bb5-4efe-9b32-e90962683e71'],providerPin:a.deadlineProvider},interpretMethodObservation);
const method=mode==='coder'?await require('./capture-method.cjs')(c,s,{operations,record}):await require('./routing-method.cjs')({...prep,directoryContext:{...prep.directoryContext,resource:c.resourceRecord}},c,s,{operations,record});
function persist(){s.deadlines=[...watches].map(([id,h])=>({id,...h.snapshot()}));save(sf,s);}
function owned(r){return r.workspace_id===ws&&r.runtime_id===runtime&&s.ownedIssues.includes(r.issue_id)&&typeof r.id==='string';}
function bind(rows){if(!Array.isArray(rows))throw Error('RUN_SHAPE');for(const r of rows){if(!owned(r))throw Error('RUN_IDENTITY');s.boundRuns[r.id]=r;if(terminal(r)&&watches.has(r.id))watches.get(r.id).markTerminal(r);}}
async function cancelOutstanding(){for(const r of Object.values(s.boundRuns).filter(r=>owned(r)&&!terminal(r))){const label='phaseZG-'+key+'-cancel-'+r.id;if(fs.existsSync(label+'.operation.json'))continue;try{await op(label,['issue','cancel-task',r.id,'--issue',r.issue_id,'--output','json'],'cancels',key,closureOperationTimeout(closureTargetMono));}catch(e){s.cancelErrors??=[];s.cancelErrors.push({id:r.id,error:e.message,outcome:'UNKNOWN_NO_RETRY'});}persist();}}
function claimStop(reason,detail=null){if(caseStop)return stopPromise;caseStop={reason,detail,at:new Date().toISOString()};closureTargetMono=performance.now()+60000;s.closureDeadlineAt=new Date(Date.now()+60000).toISOString();s.firstStop=caseStop;clearTimeout(pendingTimer);clearTimeout(dispatchTimer);fs.writeFileSync('PHASE-ZG-'+key+'-FIRST-STOP.json',JSON.stringify(caseStop,null,2)+'\n',{flag:'wx'});persist();stopPromise=cancelOutstanding();return stopPromise;}
function stop(reason,detail){const p=claimStop(reason,detail);for(const h of watches.values())h.stop(reason==='CASE_TIMEOUT'?'CASE_TIMEOUT':reason==='OPERATION_FAILED'?'OPERATION_FAILED':'SCOPE_STOP');return p;}
function arm(r){if(!owned(r))throw Error('RUN_IDENTITY');s.boundRuns[r.id]=r;if(watches.has(r.id)){if(terminal(r))watches.get(r.id).markTerminal(r);return;}if(terminal(r))return;if(r.status==='dispatched'&&r.started_at===null){s.pendingNativeRuns??={};s.pendingNativeRuns[r.id]={status:r.status,started_at:null,caseDeadlineOnly:true};return;}if(r.status!=='running')throw Error('RUN_NOT_RUNNING');const budget=Math.max(1,initialDeadline-Date.parse(r.started_at));const h=startOwnedCaptureDeadline({workspace:ws,issue:r.issue_id,actor:r.agent_id,runtime,run:r,budgetMs:budget},snap=>claimStop('CASE_TIMEOUT',{run:r.id,deadline:snap}));watches.set(r.id,h);persist();}
function pendingDeadline(pending){s.pendingDispatch=!!pending;}
async function observe(label,args){if(caseStop)throw Error('CLOSURE_ONLY');const result=await op(label,args,'activeReads',key);if(args[0]==='issue'&&args[1]==='runs')bind(result);if(caseStop)throw Error('CLOSURE_ONLY');return result;}
function classify(trace,r){if(!Array.isArray(trace)||trace.some((t,j)=>t.seq!==j+1||t.task_id!==r.id||t.issue_id!==r.issue_id))throw Error('TRACE_BINDING_GAP');if(method.setTrace)method.setTrace(trace);for(const t of trace.filter(t=>['tool_use','tool_call'].includes(t.type))){if(s.requests.some(v=>v.run===r.id&&v.seq===t.seq))continue;const reasons=method.scope(t,r);s.requests.push({run:r.id,seq:t.seq,tool:t.tool,input:t.input,reasons});if(reasons.length)s.violations.push(...reasons.map(reason=>({reason,run:r.id,seq:t.seq})));}if(s.requests.length>(mode==='coder'?96:key==='T1'?64:120))s.violations.push({reason:'TOOL_REQUEST_BOUND'});}
function childrenOf(x){return Array.isArray(x)?x:[...(x.unstaged||[]),...(x.stages||[]).flatMap(v=>v.issues||v.children||[])];}
function bindChildren(x){const flat=childrenOf(x);s.children=flat;if((x.total||flat.length)>(mode==='coder'||key==='T1'?0:1))throw Error('EXCESS_CHILDREN');for(const kid of flat){if(!kid.id||method.childIdentityScope(kid).length)throw Error('CHILD_IDENTITY');if(!s.ownedIssues.includes(kid.id))s.ownedIssues.push(kid.id);s.ownedChildRefs??={};s.ownedChildRefs[kid.id]=kid.identifier||kid.id;}return flat;}
async function reserved(label,args){const result=await op(label,args,'closureReads',key,caseStop?closureOperationTimeout(closureTargetMono):20000);if(caseStop)closureOperationTimeout(closureTargetMono);return result;}
async function terminalTrace(prefix,r){if(![c.actor,'9e98e1d4-7bb5-4efe-9b32-e90962683e71'].includes(r.agent_id)){s.unapprovedTraceNotRead??=[];s.unapprovedTraceNotRead.push(r.id);return;}const file=prefix+'-terminal-trace-'+r.id;const trace=await reserved(file,['issue','run-messages',r.id,'--issue',r.issue_id,'--output','json']);classify(trace,r);s.traces??={};s.traces[r.id]=file+'.stdout';const tail=await reserved(prefix+'-tail-'+r.id,['issue','run-messages',r.id,'--issue',r.issue_id,'--since',String(trace.at(-1)?.seq||0),'--output','json']);if(!Array.isArray(tail)||tail.length)throw Error('TERMINAL_TAIL_NOT_EMPTY');}
async function closeStopped(){await stopPromise;const end=closureTargetMono;for(let n=1;n<=6;n++){const prefix='phaseZG-'+key+'-closure-'+n;
 try{const kids=await reserved(prefix+'-children',['issue','children',c.issue,'--output','json']);bindChildren(kids);for(const issue of s.ownedIssues)bind(await reserved(prefix+'-runs-'+issue,['issue','runs',issue,'--output','json']));s.runs=Object.values(s.boundRuns);await cancelOutstanding();
 if(s.runs.length&&s.runs.every(terminal)){for(const r of s.runs)await terminalTrace(prefix,r);for(const h of watches.values())await h.done;s.terminalKnownRuns=true;s.complete=!s.pendingDispatch&&!s.unapprovedTraceNotRead?.length;s.executorStopped=true;s.completedAt=new Date().toISOString();persist();console.log(JSON.stringify({key,firstStop:caseStop,runs:s.runs.map(r=>({id:r.id,status:r.status})),complete:s.complete,pendingDispatch:s.pendingDispatch}));return;}
 }catch(e){s.closureErrors??=[];s.closureErrors.push({at:new Date().toISOString(),error:e.message});persist();}
 if(performance.now()>=end)break;await new Promise(r=>setTimeout(r,Math.min(10000,Math.max(0,end-performance.now()))));}
 s.complete=false;s.executorStopped=true;s.closureOutcome='UNKNOWN_TERMINAL_OR_PENDING_DISPATCH';persist();throw Error('TERMINAL_CLOSURE_UNVERIFIED');}
const assigned=await op('phaseZG-'+key+'-assign',c.assignArgv,'triggers',key);s.assignReceipt=pin('phaseZG-'+key+'-assign.stdout');assignmentAckMono=performance.now();dispatchTimer=setTimeout(()=>stop('DISPATCH_START_TIMEOUT',{deadlineFrom:'ASSIGNMENT_ACK_MONOTONIC_30S',noFakeStart:true}),30000);persist();
for(;;){const prefix='phaseZG-'+key+'-poll-'+String(++s.polls).padStart(3,'0');
try{
 const parents=await observe(prefix+'-runs',['issue','runs',c.issue,'--output','json']);s.runs=parents;
 const initial=mode==='coder'?parents.find(r=>r.agent_id===c.actor&&r.kind==='direct'&&r.attribution?.evidence?.kind==='issue_assignment'&&r.attribution.evidence.ref_id===c.issue):method.selectInitial(parents);
 if(!initial){if(parents.length)throw Error('INITIAL_ASSIGNMENT_BINDING');if(s.polls>3)throw Error('INITIAL_RUN_ABSENT');await new Promise(r=>setTimeout(r,1000));continue;}
 if(s.subjectRunId&&s.subjectRunId!==initial.id)throw Error('INITIAL_RUN_CHANGED');s.subjectRunId=initial.id;if(initialStartDisposition(initial)==='WAIT_DISPATCH_ACK'){s.dispatchWaiting={actualStatus:initial.status,actualStartedAt:initial.started_at,reads:++dispatchWaitReads,fromAssignmentAckMs:performance.now()-assignmentAckMono};persist();if(dispatchWaitReads>=3){await stop('DISPATCH_START_TIMEOUT','PRESTART_READ_BOUND_3');throw Error('CLOSURE_ONLY');}await new Promise(r=>setTimeout(r,Math.min(10000,Math.max(0,30000-performance.now()+assignmentAckMono))));if(caseStop)return await closeStopped();continue;}clearTimeout(dispatchTimer);if(initialDeadline===null){initialDeadline=initialDeadlineAt(initial.started_at);caseTargetMono=performance.now()+initialDeadline-Date.now();pendingTimer=setTimeout(()=>stop('CASE_TIMEOUT',{deadlineAt:new Date(initialDeadline).toISOString(),pendingDispatch:!!s.pendingDispatch,knownRunIds:Object.keys(s.boundRuns),noInventedRun:true}),Math.max(0,caseTargetMono-performance.now()));}if(!Number.isFinite(initialDeadline))throw Error('INITIAL_START_ABSENT');
 for(const r of parents)arm(r);if(caseStop)throw Error('CLOSURE_ONLY');
 if(mode==='coder'){
 if(parents.length!==1||initial.agent_id!==c.actor||initial.is_leader_task===true)throw Error('EXCESS_OR_WRONG_DIRECT_RUN');const cwd=initial.work_dir||initial.result?.work_dir;if(cwd&&![c.cwd,c.logicalCwd].includes(cwd))throw Error('DIRECT_ROOT_MISMATCH');s.directoryBinding=cwd?'MATCH_PUBLIC_PROJECT_ROOT_METADATA':'PENDING_ACTUAL_ROOT_BINDING';method.snapshot();if(s.violations.length){await stop('SCOPE_STOP',s.violations);throw Error('CLOSURE_ONLY');}
 }else{
 method.setPrefix(prefix);const comments=await observe(prefix+'-comments',['issue','comment','list',c.issue,'--full','--output','json']);if(!Array.isArray(comments))throw Error('COMMENT_SHAPE');s.comments=comments;
 const flat=bindChildren(await observe(prefix+'-children',['issue','children',c.issue,'--output','json']));let childWaiting=false;for(const kid of flat){const rows=await observe(prefix+'-child-runs-'+kid.id,['issue','runs',kid.id,'--output','json']);s.runs.push(...rows);if(!rows.length)childWaiting=true;for(const r of rows)arm(r);}
 const producers=s.runs.filter(r=>r.agent_id==='9e98e1d4-7bb5-4efe-9b32-e90962683e71'),coords=parents.filter(r=>r.agent_id===c.actor);if(producers.length>(key==='T1'?0:1)||coords.length>(key==='T1'?1:2)||s.runs.some(r=>![c.actor,'9e98e1d4-7bb5-4efe-9b32-e90962683e71'].includes(r.agent_id)))throw Error('UNAPPROVED_TOPOLOGY_OR_ACTOR');if(s.runs.length>3||producers.some(r=>r.issue_id===c.issue)&&flat.length)throw Error('MIXED_OR_EXCESS_TOPOLOGY');
 s.sameIssueBindingPending=false;s.childPending=childWaiting||s.runs.some(r=>r.issue_id!==c.issue&&!terminal(r));s.directoryBindings={};for(const r of s.runs){const view=method.directoryView(r,coords);s.directoryBindings[r.id]=view;record('inspectNativeDirectoryBinding',view,r,{kind:'RUN_METADATA'});if(view.status==='SCOPE_REJECT')throw Error(view.reason);}
 for(const r of producers.filter(r=>r.issue_id===c.issue)){const source=coords.find(v=>v.id===r.attribution?.delegated_from_task_id),comment=comments.find(v=>v.id===r.trigger_comment_id),view=source&&comment?method.bindSame(comment.content,source,method.delegationContext(),{stage:'bound',comment,run:r,coderRuns:producers}):{status:'PENDING_PUBLIC_DELEGATION_EVIDENCE'};s.sameIssueBinding=view;record('inspectSameIssueCoderDelegation',view,r,{kind:'RUN_METADATA'});if(view.status==='MATCH_SAME_ISSUE_CODER_RUN')s.sameIssueCoderRun=r.id;else if(view.status==='SCOPE_REJECT')throw Error(view.reason);else s.sameIssueBindingPending=true;}
 if(coords.length===2){s.replyWakeup=method.replyWakeup(s.runs,comments);record('inspectOwnedReplyWakeup',s.replyWakeup,coords[1],{kind:'RUN_METADATA'});if(s.replyWakeup.status==='SCOPE_REJECT')throw Error(s.replyWakeup.reason);s.structuredEventAcceptance='PENDING_REQUIRED_STRUCTURED_EVENT';}
 if(caseStop)throw Error('CLOSURE_ONLY');method.inventory();if(s.violations.length){await stop('SCOPE_STOP',s.violations);throw Error('CLOSURE_ONLY');}
 }
 for(const r of s.runs){const file=prefix+'-trace-'+r.id,trace=await observe(file,['issue','run-messages',r.id,'--issue',r.issue_id,'--output','json']);s.traces??={};s.traces[r.id]=file+'.stdout';classify(trace,r);if(s.violations.length){await stop('SCOPE_STOP',s.violations);throw Error('CLOSURE_ONLY');}if(terminal(r)&&watches.has(r.id))watches.get(r.id).markTerminal(r);}
 const professional=key==='T2'||key==='unfamiliar',producers=s.runs.filter(r=>r.agent_id==='9e98e1d4-7bb5-4efe-9b32-e90962683e71');pendingDeadline(dispatchPending({professional,childPending:s.childPending,sameIssueBindingPending:s.sameIssueBindingPending,sameIssueRequest:s.sameIssueRequest,producerCount:producers.length}));
 if(professional&&!caseStop){const delivered=method.eligibleProducer();if(delivered){s.componentDeliveryObserved={run:delivered.id,at:new Date().toISOString(),grade:'PRODUCER_COMPLETED_ONLY_GATES_PENDING'};await stop('COMPONENT_PRODUCER_DELIVERY_CUTPOINT');throw Error('CLOSURE_ONLY');}}
 if(s.runs.length&&s.runs.every(terminal)&&!s.pendingDispatch){clearTimeout(pendingTimer);for(const h of watches.values())await h.done;for(const r of s.runs)await terminalTrace(prefix,r);if(mode==='coder'){bindChildren(await op(prefix+'-final-children',['issue','children',c.issue,'--output','json'],'closureReads',key));s.deliveries=method.deliveries(read(s.traces[initial.id]));}s.complete=true;s.completedAt=new Date().toISOString();persist();console.log(JSON.stringify({key,runs:s.runs.map(r=>({id:r.id,status:r.status,actor:r.agent_id})),requests:s.requests.length,violations:s.violations,deliveryFiles:s.deliveries?.filter(v=>v.status==='MATCH_COMPLETE_TEXT_LINES').length}));return;}
 persist();console.log(JSON.stringify({key,poll:s.polls,runs:s.runs.map(r=>({id:r.id,status:r.status})),pending:s.pendingDispatch}));await new Promise(r=>setTimeout(r,10000));if(caseStop)return await closeStopped();
}catch(e){if(e.message!=='CLOSURE_ONLY'){s.operationErrors??=[];s.operationErrors.push({at:new Date().toISOString(),error:e.message});await stop('OPERATION_FAILED',e.message);}return await closeStopped();}
}
}
module.exports={main,createObservationRecorder,dispatchPending,initialDeadlineAt,closureOperationTimeout,initialStartDisposition};if(require.main===module)main({evidenceRoot:process.argv[2],caseKey:process.argv[3],workspace:process.argv[4],runtime:process.argv[5],caller:process.argv[6]}).catch(e=>{console.error(e.message);process.exitCode=1;});
